### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Lolipopkingloli** [NoobMCBG/ToastBroadcaster#4]
Когда пытаюсь запустить он выдает ошибку

**Comment by NoobMCBG** [comment]
Can you put stickers on here? Can't do version of plugin this old vs with API current at

**Comment by NoobMCBG** [comment]
Sorry about this problem, I will upgrade a new version so you can experience it

**Comment by NoobMCBG** [comment]
Version 1.0.1 has been upgraded on github, you can use the plugin already!

**Comment by Lolipopkingloli** [comment]
Как мне его скачать ?
