### ISSUE TITLE
И снова я ошибки продолжаются

### ISSUE THREAD

**Issue by Lolipopkingloli** [NoobMCBG/ToastBroadcaster#7]
Server thread/CRITICAL]: pocketmine\utils\ConfigLoadException: "Failed to parse config /home/plugins/ToastBroadcaster/config.yml: yaml_parse(): scanning error encountered during parsing: block sequence entries are not allowed in this context (line 13, column 104)" (EXCEPTION) in "pmsrc/src/utils/ConfigLoadException" at line 29

**Comment by NoobMCBG** [comment]
Please remove config.yml ToastBroadcaster in plugin_data and restart this server

**Comment by Lolipopkingloli** [comment]
Как я должен добавить сообщения тогда ?
