### ISSUE TITLE
Как добавить новые сообщения

### ISSUE THREAD

**Issue by Lolipopkingloli** [NoobMCBG/ToastBroadcaster#8]
Помогите пожалуйста

**Comment by NoobMCBG** [comment]
You restart the server and access the 
ToastBroadcaster data plugin and edit the file config.yml

**Comment by Lolipopkingloli** [comment]
Еслитменятъ конфиг то оно ламаетс

**Comment by Lolipopkingloli** [comment]
Оно поломается если я там что-то добовляю

**Comment by NoobMCBG** [comment]
---
#  
#  ░████████╗░█████╗░░█████╗░░██████╗████████╗██████╗░██████╗░░█████╗░░█████╗░██████╗░░█████╗░░█████╗░░██████╗████████╗███████╗██████╗░
#  ░╚══██╔══╝██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗
#  ░░░░██║░░░██║░░██║███████║╚█████╗░░░░██║░░░██████╦╝██████╔╝██║░░██║███████║██║░░██║██║░░╚═╝███████║╚█████╗░░░░██║░░░█████╗░░██████╔╝
#  ░░░░██║░░░██║░░██║██╔══██║░╚═══██╗░░░██║░░░██╔══██╗██╔══██╗██║░░██║██╔══██║██║░░██║██║░░██╗██╔══██║░╚═══██╗░░░██║░░░██╔══╝░░██╔══██╗
#  ░░░░██║░░░╚█████╔╝██║░░██║██████╔╝░░░██║░░░██████╦╝██║░░██║╚█████╔╝██║░░██║██████╔╝╚█████╔╝██║░░██║██████╔╝░░░██║░░░███████╗██║░░██║
#  ░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝
title: "§d[ToastBroadcaster]" # Title toast
broadcast:
  delay: 60 # Delay message
  message: # All message broadcast
  - "Hi Everyone"
  - "Hello"
  - "Hi"
  - "Play game"
  - "Hi bro"
...



Вот пример

**Comment by NoobMCBG** [comment]
Возможно, вам не хватает символов, чтобы закончить их

**Comment by Lolipopkingloli** [comment]
[Server thread/CRITICAL]: ErrorException: "Trying to access array offset on value of type null" (EXCEPTION) in "plugins/ToastBroadcaster(1).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster" at line 24

**Comment by Lolipopkingloli** [comment]
---
#
# ░████████╗░█████╗░░█████╗░░██████╗████████╗██████╗░██████╗░░█████╗░░█████╗░██████╗░░█████╗░░█████╗░░██████╗████████╗███████╗██████╗░
# ░╚══██╔══╝██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗
# ░░░░██║░░░██║░░██║███████║╚█████╗░░░░██║░░░██████╦╝██████╔╝██║░░██║███████║██║░░██║██║░░╚═╝███████║╚█████╗░░░░██║░░░█████╗░░██████╔╝
# ░░░░██║░░░██║░░██║██╔══██║░╚═══██╗░░░██║░░░██╔══██╗██╔══██╗██║░░██║██╔══██║██║░░██║██║░░██╗██╔══██║░╚═══██╗░░░██║░░░██╔══╝░░██╔══██╗
# ░░░░██║░░░╚█████╔╝██║░░██║██████╔╝░░░██║░░░██████╦╝██║░░██║╚█████╔╝██║░░██║██████╔╝╚█████╔╝██║░░██║██████╔╝░░░██║░░░███████╗██║░░██║
# ░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝
title: "§d[§6GUARD§4GAME§d]" # Title toast
broadcast:
delay: 60 # Delay message
message: # All message broadcast
- "§a1"
- "§b2"
- "§c3"
...

**Comment by Lolipopkingloli** [comment]
Я сменил только имя

**Comment by NoobMCBG** [comment]
Нужно уточнить, что вы изменили?

**Comment by Lolipopkingloli** [comment]
Исправьте пожалуйста

**Comment by Lolipopkingloli** [comment]
Я изменил имя  ToastBroadcaster

**Comment by NoobMCBG** [comment]
Вам разрешено редактировать только файл config.yml

**Comment by NoobMCBG** [comment]
Пожалуйста, вставьте ошибку сюда

**Comment by Lolipopkingloli** [comment]
[Server thread/CRITICAL]: ErrorException: "Trying to access array offset on value of type null" (EXCEPTION) in "plugins/ToastBroadcaster(1).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster" at line 24

**Comment by NoobMCBG** [comment]
я знаю, где ты ошибся

**Comment by NoobMCBG** [comment]
попробуй исправить так

**Comment by NoobMCBG** [comment]
Để tôi chỉnh sửa lại code nhé !!! Xin lỗi bạn vì điều này

**Comment by Lolipopkingloli** [comment]
ни

[14:26:07.548] [Server thread/INFO]: Enabling ToastBroadcaster v1.0.1

[14:26:07.550] [Server thread/CRITICAL]: ErrorException: "Trying to access array offset on value of type null" (EXCEPTION) in "plugins/ToastBroadcaster(1).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster" at line 24

--- Stack trace ---

#0 plugins/ToastBroadcaster(1).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster(24): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[51] Trying to access array offset on value of type null, string[96] phar:///home/plugins/ToastBroadcaster(1).phar/src/NoobMCBG/ToastBroadcaster/Toas, int 24)

#1 pmsrc/src/plugin/PluginBase(118): NoobMCBG\ToastBroadcaster\ToastBroadcaster->onEnable()

#2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)

#3 pmsrc/src/Server(1418): pocketmine\plugin\PluginManager->enablePlugin(object NoobMCBG\ToastBroadcaster\ToastBroadcaster#22159)

#4 pmsrc/src/Server(1031): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21903)

#5 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#5, string[6] /home/, string[14] /home/plugins/)

#6 pmsrc/src/PocketMine(362): pocketmine\server()

#7 pmsrc(11): require(string[65] phar:///GameServer/Software/PocketMine-MP.phar/src/PocketMine.php)

--- End of exception information ---

[14:26:07.550] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

[14:26:07.554] [Server thread/EMERGENCY]: Please upload the "/home/crashdumps/Thu_Jan_26-14.26.07-MSK_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

[14:26:07.555] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by NoobMCBG** [comment]
Download new link: https://github.com/NoobMCBG/ToastBroadcaster/releases/download/1.0.1/ToastBroadcaster.phar

**Comment by NoobMCBG** [comment]
Как вы? они работают?

**Comment by Lolipopkingloli** [comment]
Нет не работает

**Comment by Lolipopkingloli** [comment]
[Server thread/CRITICAL]: ErrorException: "Trying to access array offset on value of type null" (EXCEPTION) in "plugins/ToastBroadcaster (3).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster" at line 24

--- Stack trace ---

#0 plugins/ToastBroadcaster (3).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster(24): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[51] Trying to access array offset on value of type null, string[97] phar:///home/plugins/ToastBroadcaster (3).phar/src/NoobMCBG/ToastBroadcaster/Toa, int 24)

#1 pmsrc/src/plugin/PluginBase(118): NoobMCBG\ToastBroadcaster\ToastBroadcaster->onEnable()

#2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)

#3 pmsrc/src/Server(1418): pocketmine\plugin\PluginManager->enablePlugin(object NoobMCBG\ToastBroadcaster\ToastBroadcaster#22215)

#4 pmsrc/src/Server(1031): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21903)

#5 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#5, string[6] /home/, string[14] /home/plugins/)

#6 pmsrc/src/PocketMine(362): pocketmine\server()

#7 pmsrc(11): require(string[65] phar:///GameServer/Software/PocketMine-MP.phar/src/PocketMine.php)

--- End of exception information ---

[14:50:29.478] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

[14:50:29.483] [Server thread/EMERGENCY]: Please upload the "/home/crashdumps/Thu_Jan_26-14.50.29-MSK_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

[14:50:29.483] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by Lolipopkingloli** [comment]
if you don't touch config, then everything is fine, but if I change at least one letter there, everything breaks

**Comment by NoobMCBG** [comment]
Để tôi thử lại lần cuối

**Comment by Lolipopkingloli** [comment]
Хорошо

**Comment by NoobMCBG** [comment]
https://github.com/NoobMCBG/ToastBroadcaster/releases/download/1.0.1/ToastBroadcaster.1.phar

**Comment by NoobMCBG** [comment]
Please delete plugin_data ToastBroadcaster

**Comment by NoobMCBG** [comment]
Restart and edit in plugin_data/ToastBroadcaster/config.yml

**Comment by NoobMCBG** [comment]
надеюсь в этот раз получится 😦😦😦

**Comment by Lolipopkingloli** [comment]
Я каждый раз удалял конфиг

**Comment by Lolipopkingloli** [comment]
Щас проверю

**Comment by NoobMCBG** [comment]
Время ожидания пришло

**Comment by NoobMCBG** [comment]
Попробуйте отредактировать их, как раньше, и посмотрите, как они выглядят.

**Comment by Lolipopkingloli** [comment]
[Server thread/CRITICAL]: ErrorException: "Trying to access array offset on value of type null" (EXCEPTION) in "plugins/ToastBroadcaster.1 (1).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster" at line 24

--- Stack trace ---

#0 plugins/ToastBroadcaster.1 (1).phar/src/NoobMCBG/ToastBroadcaster/ToastBroadcaster(24): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[51] Trying to access array offset on value of type null, string[99] phar:///home/plugins/ToastBroadcaster.1 (1).phar/src/NoobMCBG/ToastBroadcaster/T, int 24)

#1 pmsrc/src/plugin/PluginBase(118): NoobMCBG\ToastBroadcaster\ToastBroadcaster->onEnable()

#2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)

#3 pmsrc/src/Server(1418): pocketmine\plugin\PluginManager->enablePlugin(object NoobMCBG\ToastBroadcaster\ToastBroadcaster#22371)

#4 pmsrc/src/Server(1031): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21906)

#5 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#5, string[6] /home/, string[14] /home/plugins/)

#6 pmsrc/src/PocketMine(362): pocketmine\server()

#7 pmsrc(11): require(string[65] phar:///GameServer/Software/PocketMine-MP.phar/src/PocketMine.php)

--- End of exception information ---

[15:07:15.233] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

[15:07:15.238] [Server thread/EMERGENCY]: Please upload the "/home/crashdumps/Thu_Jan_26-15.07.15-MSK_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

[15:07:15.238] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by Lolipopkingloli** [comment]
Всё так же ломает

**Comment by NoobMCBG** [comment]
скинь мне свой конфиг

**Comment by NoobMCBG** [comment]
._.

**Comment by Lolipopkingloli** [comment]
---
#
# ░████████╗░█████╗░░█████╗░░██████╗████████╗██████╗░██████╗░░█████╗░░█████╗░██████╗░░█████╗░░█████╗░░██████╗████████╗███████╗██████╗░
# ░╚══██╔══╝██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝██╔════╝██╔══██╗
# ░░░░██║░░░██║░░██║███████║╚█████╗░░░░██║░░░██████╦╝██████╔╝██║░░██║███████║██║░░██║██║░░╚═╝███████║╚█████╗░░░░██║░░░█████╗░░██████╔╝
# ░░░░██║░░░██║░░██║██╔══██║░╚═══██╗░░░██║░░░██╔══██╗██╔══██╗██║░░██║██╔══██║██║░░██║██║░░██╗██╔══██║░╚═══██╗░░░██║░░░██╔══╝░░██╔══██╗
# ░░░░██║░░░╚█████╔╝██║░░██║██████╔╝░░░██║░░░██████╦╝██║░░██║╚█████╔╝██║░░██║██████╔╝╚█████╔╝██║░░██║██████╔╝░░░██║░░░███████╗██║░░██║
# ░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝
title: "§d[GUARDGAME]" # Title toast
broadcast:
delay: "60" # Delay message
message: # All message broadcast
- "§a1"
- "§b2"
- "§c3"
...

**Comment by NoobMCBG** [comment]
Để tôi thử lần nữa :)

**Comment by Lolipopkingloli** [comment]
Хорошо, я готов с тобой работать, пока мы не победим его, ты хороший человек)

**Comment by NoobMCBG** [comment]
https://github.com/NoobMCBG/ToastBroadcaster/releases/download/1.0.1/ToastBroadcaster.2.phar

**Comment by NoobMCBG** [comment]
Спасибо за комплимент

**Comment by Lolipopkingloli** [comment]
Буду пробовать

**Comment by NoobMCBG** [comment]
На этот раз вам просто нужно установить плагин

**Comment by Lolipopkingloli** [comment]
Хорошо

**Comment by Lolipopkingloli** [comment]
Не хочу разочаровывать

**Comment by NoobMCBG** [comment]
они работают?

**Comment by Lolipopkingloli** [comment]
Нужно попытаться снова

**Comment by Lolipopkingloli** [comment]
[Server thread/CRITICAL]: ErrorException: "Trying to access array offset on value of type null" (EXCEPTION) in "plugins/ToastBroadcaster.2.phar/src/NoobMCBG/ToastBroadcaster/task/ToastBroadcasterTask" at line 21

--- Stack trace ---

#0 plugins/ToastBroadcaster.2.phar/src/NoobMCBG/ToastBroadcaster/task/ToastBroadcasterTask(21): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[51] Trying to access array offset on value of type null, string[104] phar:///home/plugins/ToastBroadcaster.2.phar/src/NoobMCBG/ToastBroadcaster/task/, int 21)

#1 pmsrc/src/scheduler/TaskHandler(123): NoobMCBG\ToastBroadcaster\task\ToastBroadcasterTask->onRun()

#2 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()

#3 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 1)

#4 pmsrc/src/Server(1812): pocketmine\plugin\PluginManager->tickSchedulers(int 1)

#5 pmsrc/src/Server(1701): pocketmine\Server->tick()

#6 pmsrc/src/Server(1062): pocketmine\Server->tickProcessor()

#7 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#5, string[6] /home/, string[14] /home/plugins/)

#8 pmsrc/src/PocketMine(362): pocketmine\server()

#9 pmsrc(11): require(string[65] phar:///GameServer/Software/PocketMine-MP.phar/src/PocketMine.php)

--- End of exception information ---

[15:15:31.980] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

[15:15:31.985] [Server thread/EMERGENCY]: Please upload the "/home/crashdumps/Thu_Jan_26-15.15.31-MSK_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

[15:15:31.985] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by NoobMCBG** [comment]
:(

**Comment by Lolipopkingloli** [comment]
Я жду

**Comment by NoobMCBG** [comment]
Tôi biết rồi, tôi đang sửa chúng, và kết thúc ngay bây giờ, chúng ta đã có thể đánh bại hắn

**Comment by Lolipopkingloli** [comment]
Хорошо братан

**Comment by NoobMCBG** [comment]
https://github.com/NoobMCBG/ToastBroadcaster/releases/download/1.0.1/ToastBroadcaster.3.phả

**Comment by NoobMCBG** [comment]
Давайте попробуем вместе

**Comment by NoobMCBG** [comment]
Я утверждаю и уверен, что на этот раз будет успешным

**Comment by NoobMCBG** [comment]
Как дела дружище

**Comment by Lolipopkingloli** [comment]
Пришли ещё рассылку

**Comment by Lolipopkingloli** [comment]
Та не работаеь

**Comment by Lolipopkingloli** [comment]
Не работает ссылка не могу скачать

**Comment by NoobMCBG** [comment]
https://github.com/NoobMCBG/ToastBroadcaster/releases/download/1.0.1/ToastBroadcaster.3.phar

**Comment by Lolipopkingloli** [comment]
Можно снова отправить мне Фаил !?

**Comment by NoobMCBG** [comment]
Hãy thử lại

**Comment by NoobMCBG** [comment]
Bạn truy cập vào được liên kết mới chứ ?

**Comment by Lolipopkingloli** [comment]
Server thread/CRITICAL]: TypeError: "count(): Argument #1 ($value) must be of type Countable|array, null given" (EXCEPTION) in "plugins/ToastBroadcaster.3.phar/src/NoobMCBG/ToastBroadcaster/task/ToastBroadcasterTask" at line 23

--- Stack trace ---

#0 plugins/ToastBroadcaster.3.phar/src/NoobMCBG/ToastBroadcaster/task/ToastBroadcasterTask(23): count(null)

#1 pmsrc/src/scheduler/TaskHandler(123): NoobMCBG\ToastBroadcaster\task\ToastBroadcasterTask->onRun()

#2 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()

#3 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 1)

#4 pmsrc/src/Server(1812): pocketmine\plugin\PluginManager->tickSchedulers(int 1)

#5 pmsrc/src/Server(1701): pocketmine\Server->tick()

#6 pmsrc/src/Server(1062): pocketmine\Server->tickProcessor()

#7 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#5, string[6] /home/, string[14] /home/plugins/)

#8 pmsrc/src/PocketMine(362): pocketmine\server()

#9 pmsrc(11): require(string[65] phar:///GameServer/Software/PocketMine-MP.phar/src/PocketMine.php)

--- End of exception information ---

[15:28:41.332] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

[15:28:41.337] [Server thread/EMERGENCY]: Please upload the "/home/crashdumps/Thu_Jan_26-15.28.41-MSK_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

[15:28:41.338] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by Lolipopkingloli** [comment]
Может прислать крашдамп?

**Comment by NoobMCBG** [comment]
._.

**Comment by Lolipopkingloli** [comment]
У меня такое же лицо

**Comment by Lolipopkingloli** [comment]
Прежде чем писать тебе я пытался сделать сам у меня не вышло (((

**Comment by NoobMCBG** [comment]
Delete plugin_data please

**Comment by Lolipopkingloli** [comment]
Ok

**Comment by NoobMCBG** [comment]
Должен стараться больше

**Comment by Lolipopkingloli** [comment]
Где удалить plugin_data ?

**Comment by NoobMCBG** [comment]
удалить раздел ToastBroadcaster в данных .плагин

**Comment by Lolipopkingloli** [comment]
Ok

**Comment by Lolipopkingloli** [comment]
Есть мессенджер ?

**Comment by Lolipopkingloli** [comment]
Я пришлю видео

**Comment by Lolipopkingloli** [comment]
Uploading Screenrecorder-2023-01-26-21-36-17-122.mp4…

**Comment by NoobMCBG** [comment]
I'm in Vietnam

**Comment by Lolipopkingloli** [comment]
Discord ? VK ? Watsap? Telegram ?

**Comment by NoobMCBG** [comment]
мы не можем отправить видео сюда

**Comment by Lolipopkingloli** [comment]
Оно не отправляется

**Comment by Lolipopkingloli** [comment]
Секунду

**Comment by NoobMCBG** [comment]
Пожалуйста, перезапустите сервер

**Comment by NoobMCBG** [comment]
Пожалуйста, перезапустите сервер

**Comment by Lolipopkingloli** [comment]
Я вам пришлю видео подождите

**Comment by NoobMCBG** [comment]
Я знаю, как они работают, следуй моему примеру

**Comment by Lolipopkingloli** [comment]
https://www.veed.io/view/f98bd1ab-491e-4ddf-94e0-642b14829d4e?sharingWidget=true&panel=share

**Comment by Lolipopkingloli** [comment]
Оно работает пока я ничего не трогаю

**Comment by NoobMCBG** [comment]
Пожалуйста, удалите ToastBroadcaster в plugin_data, т.к. на моем устройстве при тестировании они все нормально работают

**Comment by NoobMCBG** [comment]
Tôi đã xem video

**Comment by Lolipopkingloli** [comment]
Я что-то не то удаляю?

**Comment by NoobMCBG** [comment]
Bây giờ bạn đi tới file plugin_data và xoá hẳn file ToastBroadcaster đi và làm lại

**Comment by NoobMCBG** [comment]
Rõ ràng là trên thiết bị của tôi, mặc dù tôi có thay đổi hay không thay đổi thì chúng đều hoạt động 1 cách bình thường

**Comment by Lolipopkingloli** [comment]
Я не могу найти плагин_дата

**Comment by NoobMCBG** [comment]
вы выбираете файл plugin_data

**Comment by NoobMCBG** [comment]
затем удалите файл ToastBroadcaster

**Comment by NoobMCBG** [comment]
следуй моим инструкциям

**Comment by Lolipopkingloli** [comment]
Есть только папка plugins

**Comment by Lolipopkingloli** [comment]
Я удалил и Фаил и папку ToastBroadcaster

**Comment by NoobMCBG** [comment]
hãy bắt đầu máy chủ

**Comment by Lolipopkingloli** [comment]
Без файлов ?

**Comment by NoobMCBG** [comment]
only need to back ToastBroadcaster.3.phar in the plugins directory is being

**Comment by Lolipopkingloli** [comment]
Ok

**Comment by NoobMCBG** [comment]
Start server

**Comment by Lolipopkingloli** [comment]
Зас я загружу снова

**Comment by NoobMCBG** [comment]
Okay

**Comment by NoobMCBG** [comment]
Sao rồi

**Comment by Lolipopkingloli** [comment]
Запустил он работает, но ничего не менял

**Comment by NoobMCBG** [comment]
HÃY THỬ THAY ĐỔI CHUNGA

**Comment by NoobMCBG** [comment]
hãy thử thay đổi chúng

**Comment by NoobMCBG** [comment]
Sao rồi anh bạn

**Comment by Lolipopkingloli** [comment]
Не работает (((

**Comment by NoobMCBG** [comment]
как ни странно, на моем устройстве все работает очень гладко, без каких-либо проблем

**Comment by Lolipopkingloli** [comment]
Может ядро у меня другое

**Comment by NoobMCBG** [comment]
К сожалению :(

**Comment by NoobMCBG** [comment]
Но это нормально, мы также можем общаться друг с другом через Интернет.

**Comment by Lolipopkingloli** [comment]
И что мне с этим делать ? Почему когда я просто устанавливаю всё, работает

**Comment by Lolipopkingloli** [comment]
Щас я попробую загрузить на пустой сервер

**Comment by NoobMCBG** [comment]
Hãy cùng nhau thử lại phiên bản cuối cùng

**Comment by Lolipopkingloli** [comment]
Это не работает на другом сервере

**Comment by NoobMCBG** [comment]
https://www.mediafire.com/file/wznumcw0cmzsgjt/ToastBroadcaster+(4).phar/file

**Comment by Lolipopkingloli** [comment]
Хорошо давай попробуем

**Comment by NoobMCBG** [comment]
Yes

**Comment by NoobMCBG** [comment]
Chúng hoạt động không ?

**Comment by NoobMCBG** [comment]
Có lẽ đây sẽ là lần cuối

**Comment by NoobMCBG** [comment]
Vì tôi có việc mất rồi

**Comment by Lolipopkingloli** [comment]
Брат иди работать оно снова не работает нужно стараться лучше я попрошу друга помочь

**Comment by NoobMCBG** [comment]
Спасибо

**Comment by NoobMCBG** [comment]
Good bye

**Comment by NoobMCBG** [comment]
Chúc may mắn
